"""first migration

Revision ID: 006bc1bec7d3
Revises: 
Create Date: 2020-10-11 15:47:51.880811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006bc1bec7d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('localized_name', sa.String(length=50), nullable=True),
    sa.Column('primary_attr', sa.String(length=3), nullable=True),
    sa.Column('attack_type', sa.String(length=10), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('base_health', sa.Integer(), nullable=True),
    sa.Column('base_health_regen', sa.Integer(), nullable=True),
    sa.Column('base_mana', sa.Integer(), nullable=True),
    sa.Column('base_mana_regen', sa.Integer(), nullable=True),
    sa.Column('base_armor', sa.Integer(), nullable=True),
    sa.Column('base_mr', sa.Integer(), nullable=True),
    sa.Column('base_attack_min', sa.Integer(), nullable=True),
    sa.Column('base_attack_max', sa.Integer(), nullable=True),
    sa.Column('base_str', sa.Integer(), nullable=True),
    sa.Column('base_agi', sa.Integer(), nullable=True),
    sa.Column('base_int', sa.Integer(), nullable=True),
    sa.Column('str_gain', sa.Integer(), nullable=True),
    sa.Column('agi_gain', sa.Integer(), nullable=True),
    sa.Column('int_gain', sa.Integer(), nullable=True),
    sa.Column('attack_range', sa.Integer(), nullable=True),
    sa.Column('projectile_speed', sa.Integer(), nullable=True),
    sa.Column('attack_rate', sa.Integer(), nullable=True),
    sa.Column('move_speed', sa.Integer(), nullable=True),
    sa.Column('turn_rate', sa.Integer(), nullable=True),
    sa.Column('cm_enabled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=True),
    sa.Column('radiant_score', sa.Integer(), nullable=True),
    sa.Column('dire_score', sa.Integer(), nullable=True),
    sa.Column('radiant_team_id', sa.Integer(), nullable=True),
    sa.Column('dire_team_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pro_team_name'), 'pro_team', ['name'], unique=False)
    op.create_table('public_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_seq_num', sa.Integer(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('avg_mmr', sa.Integer(), nullable=True),
    sa.Column('num_mmr', sa.Integer(), nullable=True),
    sa.Column('lobby_type', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.Integer(), nullable=True),
    sa.Column('avg_rank_tier', sa.Integer(), nullable=True),
    sa.Column('num_rank_tier', sa.Integer(), nullable=True),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('radiant_team', sa.String(length=20), nullable=True),
    sa.Column('dire_team', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heroRoles',
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heroRoles')
    op.drop_table('role')
    op.drop_table('public_match')
    op.drop_index(op.f('ix_pro_team_name'), table_name='pro_team')
    op.drop_table('pro_team')
    op.drop_table('pro_match')
    op.drop_table('hero')
    # ### end Alembic commands ###
